### ISSUE TITLE
Broken `token_reset` pipeline

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/admin-requests#781]
Last jobs have been failing for a few hours:

```
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/cf/lib/python3.8/site-packages/conda_smithy/feedstock_tokens.py", line 455, in _register_token
    func(user, project, feedstock_token, clobber, *args)
  File "/usr/share/miniconda3/envs/cf/lib/python3.8/site-packages/conda_smithy/feedstock_tokens.py", line 658, in add_feedstock_token_to_travis
    r.raise_for_status()
  File "/usr/share/miniconda3/envs/cf/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.travis-ci.com/repo/24240621/env_var/814bc388-3cc7-452b-87b1-47d270ef0e81

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/cf/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/usr/share/miniconda3/envs/cf/lib/python3.8/site-packages/conda_smithy/cli.py", line 669, in main
    args.subcommand_func(args)
  File "/usr/share/miniconda3/envs/cf/lib/python3.8/site-packages/conda_smithy/cli.py", line 826, in __call__
    register_feedstock_token_with_providers(
  File "/usr/share/miniconda3/envs/cf/lib/python3.8/site-packages/conda_smithy/feedstock_tokens.py", line 520, in register_feedstock_token_with_providers
    raise e
  File "/usr/share/miniconda3/envs/cf/lib/python3.8/site-packages/conda_smithy/feedstock_tokens.py", line 494, in register_feedstock_token_with_providers
    _register_token(
  File "/usr/share/miniconda3/envs/cf/lib/python3.8/site-packages/conda_smithy/feedstock_tokens.py", line 464, in _register_token
    raise FeedstockTokenError(err_msg)
conda_smithy.feedstock_tokens.FeedstockTokenError: Failed to register feedstock token for conda-forge/mpltoolbox-feedstock on travis for args ()!
failed to reset token for 'mpltoolbox': CalledProcessError(1, ['conda', 'smithy', 'register-feedstock-token', '--without-circle', '--without-drone', '--without-github-actions', '--feedstock_directory', '/tmp/tmpfudbg0je/mpltoolbox-feedstock', '--organization', 'conda-forge', '--token_repo', 'https://x-access-token:${GITHUB_TOKEN}@github.com/conda-forge/feedstock-tokens'])
[main be3d73a] Keeping token_reset/mpltoolbox.txt after failed token reset
```

Is this an expired token?

cc @beckermr

**Comment by beckermr** [comment]
I doubt it. Travis just dies sometimes. Try adding a comment above the offending package like this:

```
# --without-travis
```

**Comment by jaimergp** [comment]
Ok that worked, nice! Thanks!
