### ISSUE TITLE
Trouble updating environment variables on Travis CI (token reset)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/admin-requests#855]
As part of the token reset process, we set environment variables on CI providers. Lately this has been running into 403s on Travis CI. For example (also [on CI]( https://github.com/conda-forge/admin-requests/actions/runs/6729972313/job/18291791354#step:9:38 )):

```python
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/cf/lib/python3.8/site-packages/conda_smithy/feedstock_tokens.py", line 455, in _register_token
    func(user, project, feedstock_token, clobber, *args)
  File "/usr/share/miniconda3/envs/cf/lib/python3.8/site-packages/conda_smithy/feedstock_tokens.py", line 658, in add_feedstock_token_to_travis
    r.raise_for_status()
  File "/usr/share/miniconda3/envs/cf/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.travis-ci.com/repo/12190770/env_var/8e33ebfd-c0ad-4801-bc53-abb7b0f416ea
```

Filing to document/track this issue

**Comment by jakirkham** [comment]
Thanks Filipe! 🙏 

Don't think that is related to this issue. This issue is about existing feedstocks that Travis CI already knows about, but we try to change an environment variable in.

Think that case is caused by difficulty registering repos with Travis CI, which is tracked in issue ( https://github.com/conda-forge/staged-recipes/issues/24406 ). That said, it did eventually clear ( https://github.com/conda-forge/staged-recipes/commit/420c25db7de4fa02d938db32e3f08c207607fc5d ). So think that issue is now resolved

**Comment by jakirkham** [comment]
In discussion with Travis CI, they asked to have the bot accounts..

> Can you please log out, clear browser cache/cookies, and log back in with these accounts to see if the issue is resolved?

It appears soon after doing this, [the following job passed]( https://github.com/conda-forge/admin-requests/actions/runs/6784008045/job/18439430310#step:9:55 ), which cleared out the token reset request for `sccache` ( https://github.com/conda-forge/admin-requests/commit/824dca4ddae5731bcd8abcc2f59ccc6884d0c228 )

This should fix the upload issues the feedstock was having ( https://github.com/conda-forge/sccache-feedstock/issues/27 ) , which can be seen by the recent passing build ( https://github.com/conda-forge/sccache-feedstock/commit/f3945a29c7423d83558ff5d7f8dc4d5a82828863 )

Going to close this out

Thanks everyone for your help! 🙏 

cc @beckermr (for vis)
