### ISSUE TITLE
Scheduled runs are failing

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/admin-requests#859]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Both `repodata_patching` and `create_feedstocks` are failing:

```
++ python .github/workflows/scripts/create_feedstocks.py
Traceback (most recent call last):
  File "/home/runner/work/admin-requests/admin-requests/.github/workflows/scripts/create_feedstocks.py", line 216, in <module>
    gh_remaining = print_rate_limiting_info(gh, 'GH_TOKEN')
  File "/home/runner/work/admin-requests/admin-requests/.github/workflows/scripts/create_feedstocks.py", line 142, in print_rate_limiting_info
    gh_api_reset_time -= datetime.utcnow()
TypeError: can't subtract offset-naive and offset-aware datetimes
```

```
Traceback (most recent call last):
  File "show_diff.py", line 161, in <module>
    from gen_patch_json import SUBDIRS
  File "/tmp/tmpt0c4w9vu/conda-forge-repodata-patches-feedstock/recipe/gen_patch_json.py", line 22, in <module>
    from patch_yaml_utils import (
  File "/tmp/tmpt0c4w9vu/conda-forge-repodata-patches-feedstock/recipe/patch_yaml_utils.py", line 21, in <module>
    from patch_yaml_model import PatchYaml  # noqa
  File "/tmp/tmpt0c4w9vu/conda-forge-repodata-patches-feedstock/recipe/patch_yaml_model.py", line 8, in <module>
    from typing import Annotated
ImportError: cannot import name 'Annotated' from 'typing' 
```

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

**Comment by jaimergp** [comment]
@beckermr - is it safe to run a workflow dispatch trigger in https://github.com/conda-forge/admin-requests/actions/workflows/repodata_patching.yml? Just to make sure the thing works now before waiting for a week 😬

**Comment by beckermr** [comment]
Yep. It'll make a new set of patches but that's ok.

**Comment by jaimergp** [comment]
```
TypeError: unsupported operand type(s) for |: '_AnnotatedAlias' and 'types.GenericAlias'
```

We are going to need a more recent Python I think :D

**Comment by jaimergp** [comment]
Fixed!
